name: 'Deploy Static Sites'
description: 'Deploys Static Sites using S3 and CloudFront.'
inputs:
  assume-role-arn:
    description: 'Role assumed by the action.'
    required: true
  bucket-name:
    description: 'The name of the S3 Bucket.'
    required: true
  working-directory:
    description: 'Folder the files will be synced from.'
    required: true
  cache-control-s-max-age:
    description: 'Number of seconds the information will be cached by CloudFront.'
    default: 86400
    required: false
  cloudfront-distribution:
    description: 'ID Name of CloudFront Distribution.'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.assume-role-arn }}" ]; then
          echo "Error: Missing required input: assume-role-arn"
          exit 1
        fi
        if [ -z "${{ inputs.bucket-name }}" ]; then
          echo "Error: Missing required input: bucket-name"
          exit 1
        fi
        if [ -z "${{ inputs.working-directory }}" ]; then
          echo "Error: Missing required input: working-directory"
          exit 1
        fi
        if [ -z "${{ inputs.cloudfront-distribution }}" ]; then
          echo "Error: Missing required input: cloudfront-distribution"
          exit 1
        fi

    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: ${{ inputs.assume-role-arn }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: eu-west-2

    - name: Sync
      shell: bash
      run: |
        cd ./${{ inputs.working-directory }}
        aws s3 sync . s3://${{ inputs.bucket-name }}/ --exclude ".*" --exclude "*/.*" --delete --cache-control 's-maxage=${{ inputs.cache-control-s-max-age}}'
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution }} --paths "/*"

