name: 'Deploy Static Sites'
description: 'Deploys Static Sites using S3 and CloudFront.'
inputs:
  assume-role-arn:
    description: 'Role assumed by the action.'
    required: true
  working-directory:
    description: 'Folder the files will be synced from.'
    required: true
  cache-control-s-max-age:
    description: 'Number of seconds the information will be chached by CloudFront.'
    default: 86400
    required: false
  domain:
    description: ''
    required: true
  
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: ${{ inputs.assume-role-arn }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: eu-west-2

    - name: Sync
      shell: bash
      run: |
        cd ./${{ inputs.working-directory }}
        export BUCKET_NAME=$(AWS_REGION=eu-west-2 aws ssm get-parameter --name /static-site/${{ inputs.domain }}/bucket  | jq .Parameter.Value -r)
        export DISTRIBUTION=$(AWS_REGION=eu-west-2 aws ssm get-parameter --name /static-site/${{ inputs.domain }}/cloudfront  | jq .Parameter.Value -r)
        aws s3 sync . s3://"$BUCKET_NAME"/ --exclude ".*" --exclude "*/.*" --delete --cache-control 's-maxage=${{ inputs.cache-control-s-max-age}}'
        aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION" --paths "/*"

