name: 'Deploy Static Sites'
description: 'Deploys Static Sites using S3 and Cloud Front.'
inputs:
  assume_role_arn:
    description: 'Role assumed by the action.'
    required: true
  bucket_name:
    description: 'The name of the S3 Bucket.'
    required: true
  working_directory:
    description: 'Folder the files will be synced from.'
    required: true
  cache_control_s_max_age:
    description: 'Number of seconds the information will be chached by CloudFront.'
    default: 86400
    required: false
  cloudfront_distribution:
    description: 'ID Name of CloudFront Distribution.'
    required: true
  
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: ${{ inputs.assume_role_arn }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: eu-west-2

    - name: Sync
      shell: bash
      run: |
        cd ./${{ inputs.working_directory }}
        aws s3 sync . s3://${{ inputs.bucket_name }}/ --delete --cache-control 's-maxage=${{ inputs.cache_control_s_max_age}}'
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_distribution }} --paths "/*"

