apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-cloud-static-sites-action
  annotations:
    github.com/project-slug: UKHomeOffice/core-cloud-static-sites-action
spec:
  type: service
  owner: core-cloud-devops
  lifecycle: experimental
  system: core-cloud
